{% set name = "moor" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/walles/moor/archive/v{{ version }}.tar.gz
  sha256: 99f4610298e015aeb98de3521d724e840efb24f2e7514fae1d6a8ce8f7ed7c0b

build:
  number: 0

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - go-licenses

test:
  commands:
    - moor --help

about:
  home: https://github.com/walles/moor
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  dev_url: https://github.com/walles/moor

extra:
  recipe-maintainers:
    - danielnachun
