{% set name = "moor" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/walles/moor/archive/v{{ version }}.tar.gz
  sha256: da5e3209d78ad811491ae49c50140366fcb56ddc9fc0d3a65199efe968337d33

build:
  number: 0

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - go-licenses

test:
  commands:
    - moor --help

about:
  home: https://github.com/walles/moor
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  dev_url: https://github.com/walles/moor

extra:
  recipe-maintainers:
    - danielnachun
