{% set name = "moar" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/walles/moar/archive/v{{ version }}.tar.gz
  sha256: 8530e171c281aa49d050b9b8ecf81ddb48b5de90d9dca54b2f427765085db46f

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - moar --help

about:
  home: https://github.com/walles/moar
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  dev_url: https://github.com/walles/moar

extra:
  recipe-maintainers:
    - danielnachun
