schema_version: 1

context:
  version: "2.11.0"

package:
  name: moor
  version: ${{ version }}

source:
  url: https://github.com/walles/moor/archive/v${{ version }}.tar.gz
  sha256: 091a8bba0d75354c2897029ae89604f47c63d1670ce32f4f80f10b99612dc584

build:
  number: 0

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - moor --help

about:
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  homepage: https://github.com/walles/moor
  repository: https://github.com/walles/moor

extra:
  recipe-maintainers:
    - danielnachun
