schema_version: 1

context:
  version: "2.14.0"

package:
  name: moor
  version: ${{ version }}

source:
  url: https://github.com/walles/moor/archive/v${{ version }}.tar.gz
  sha256: defac420180c46e814be9cb0819b4a8467a78adf0c34d9341909a5867755230e

build:
  number: 0

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - moor --help

about:
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  homepage: https://github.com/walles/moor
  repository: https://github.com/walles/moor

extra:
  recipe-maintainers:
    - danielnachun
