schema_version: 1

context:
  version: "2.13.4"

package:
  name: moor
  version: ${{ version }}

source:
  url: https://github.com/walles/moor/archive/v${{ version }}.tar.gz
  sha256: 83412ba2c03d399ba54b4fc18db05e1e9c29d486148f3a2ec3682f3959a0c4e1

build:
  number: 0

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - moor --help

about:
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  homepage: https://github.com/walles/moor
  repository: https://github.com/walles/moor

extra:
  recipe-maintainers:
    - danielnachun
